# Generated by Django 2.1.7 on 2019-07-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190704_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislike_person',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_person',
        ),
    ]
